CSGestion/Models/ViewModels/RegistroSolicitudViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CSGestion.Models.ViewModels
{
    public class RegistroSolicitudViewModel
    {
        [Required(ErrorMessage = "Seleccione un sector")]
        public int IdSector { get; set; }

        [Required(ErrorMessage = "Ingrese hora de inicio")]
        public string FechaHoraInicio { get; set; }

        [Required(ErrorMessage = "Ingrese hora de finalización")]
        public string FechaHoraFin { get; set; }

        [Display(Name = "Rut solicitante *")]
        [Required(ErrorMessage = "Ingrese el rut del solicitante")]
        public string RutSolicitante { get; set; }

        [Required(ErrorMessage = "Ingrese el nombre del solicitante")]
        public string NombreSolicitante { get; set; }

        [Required(ErrorMessage = "Ingrese casa o departamento")]
        public string CasaDepto { get; set; }

        public string Ubicacion { get; set; }


        public SelectList SectorList
        {
            get
            {
                var d = new List<Dummy>();
                d.Add(new Dummy { Clave = 1, Valor = "Salón de eventos A" });
                d.Add(new Dummy { Clave = 2, Valor = "Salón de eventos B" });

                return new SelectList(d, "Clave", "Valor");
            }
        }

        public SelectList UbicacionList
        {
            get
            {
                var d = new List<Dummy>();
                d.Add(new Dummy { Clave = 1, Valor = "Torre Mahuida" });
                d.Add(new Dummy { Clave = 2, Valor = "Torre B" });

                return new SelectList(d, "Clave", "Valor");
            }
        }

        public bool WithError { get; set; }

        public class Dummy
        {
            public int Clave { get; set; }
            public string Valor { get; set; }
        }

    }
}

CSGestion/Controllers/RegistroSolicitudController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CSGestion.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CSGestion.Controllers
{
    public class RegistroSolicitudController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        //public ActionResult Agregar()
        //{ 
        //    var model = new RegistroSolicitudViewModel();

        //    return PartialView(model);
        //}

        public async Task<ActionResult> Agregar()
        {

            var t = await Task.Run(() =>
            {

                var model = new RegistroSolicitudViewModel();

                return model;
            }).ConfigureAwait(false);

            return PartialView(t);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Agregar(RegistroSolicitudViewModel model)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    throw new Exception("error forzado");
                }
                else
                {
                    return PartialView(model);
                }

                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", "Un error cualquiera: " + e.Message);
                model.WithError = true;

                return PartialView(model);
            }
        }

        public ActionResult Edit(int id)
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new Models.ErrorViewModel { RequestId = System.Diagnostics.Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }

    //TODO: mtoroc, se recomienda mantener codigo para reutilizarlo en comportamiento estatico de vistas a traves de viewcomponente
    //public class RegistroSolicitudComponent : ViewComponent
    //{
    //    public IViewComponentResult Invoke(string view)
    //    {
    //        var model = new RegistroSolicitudViewModel();

    //        return View(view, model);
    //    }
    //}
}

CSGestion/Views/RegistroSolicitud/Agregar.cshtml
@model CSGestion.Models.ViewModels.RegistroSolicitudViewModel

    <div class="modal-dialog modal-dialog-centered modal-lg" role="document" id="innerModal">
        <div class="modal-content" id="modalContent">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle">Calendario de solicitudes</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            @*@using (Html.BeginForm("Agregar", "RegistroSolicitud", FormMethod.Post, new { id = "formAgregar" }))
            {*@
        <form id="formAgregar">
            @Html.AntiForgeryToken()
            <div class="modal-body">

                <div class="row @(Model.WithError ? "" : "collapse")">
                    <div class="col-md-12">
                        <div class="alert alert-danger" role="alert">
                            @Html.ValidationSummary(true, "", new { @class = "" })
                        </div>
                    </div>
                </div>


                <div class="row">
                    <div class="col-md-12 mb-3">
                        <label for="IdSector">Sector solicitado</label>
                        @Html.DropDownListFor(m => m.IdSector, Model.SectorList, "Seleccione...", new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.IdSector, null, new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="FechaHoraInicio">Fecha/Hora inicio</label>
                        <div class="input-group date">
                            @Html.TextBoxFor(m => m.FechaHoraInicio, new { @class = "form-control" })
                            <div class="input-group-addon">
                                <span class="far fa-calendar-alt fa-2x"></span>
                            </div>
                        </div>
                        @Html.ValidationMessageFor(m => m.FechaHoraInicio, null, new { @class = "text-danger" })
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="FechaHoraFin">Fecha/Hora  fin</label>
                        <div class="input-group date">
                            @Html.TextBoxFor(m => m.FechaHoraFin, new { @class = "form-control" })
                            <div class="input-group-addon">
                                <span class="far fa-calendar-alt fa-2x"></span>
                            </div>
                        </div>
                        @Html.ValidationMessageFor(m => m.FechaHoraFin, null, new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="RutSolicitante">Rut solicitante</label>
                        @Html.TextBoxFor(m => m.RutSolicitante, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.RutSolicitante, null, new { @class = "text-danger" })
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="NombreSolicitante">Nombre</label>
                        @Html.TextBoxFor(m => m.NombreSolicitante, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.NombreSolicitante, null, new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="CasaDepto">Casa / Depto</label>
                        @Html.TextBoxFor(m => m.CasaDepto, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.CasaDepto, null, new { @class = "text-danger" })
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="Ubicacion">Ubicación</label>
                        @Html.DropDownListFor(m => m.Ubicacion, Model.UbicacionList, "Seleccione...", new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Ubicacion, null, new { @class = "text-danger" })
                    </div>
                </div>


            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Agregar</button>
                <button type="button" class="btn btn-secondary form-reset" data-dismiss="modal">Cerrar</button>
            </div>
        </form>
            @*}*@

        </div>

    </div>

<script src="~/js/registro-solicitud/agregar.js"></script>

@section scripts {
    @*TODO: mtoroc, no se porque no hereda correctamente los section scripts, pero tiene que ver con rediseño de MVC core*@
}

CSGestion/Views/RegistroSolicitud/Index.cshtml
    <div clas="content-helper" style="padding-top:2.5em;">

        <div class="row">
            <div class="offset-10 col-2">
                @*<button type="button" class="btn btn-primary float-right" data-toggle="modal" data-target="#myModal">Agregar solicitud view component</button>*@
                <button type="button" class="btn btn-primary float-right" id="btnAgregarSolicitud">Agregar solicitud</button>
                
            </div>
        </div>
        <br />

        <div class="row">
            <h2>Calendario de solicitudes</h2>

            <div class="col-12 table-responsive">
                <table class="table table-hover" id="miTabla">
                    <thead>
                        <tr class="table-active">
                            <th scope="col">#</th>
                            <th scope="col">Sector</th>
                            <th scope="col">Fecha inicio</th>
                            <th scope="col">Fecha termino</th>
                            <th scope="col">Rut</th>
                            <th scope="col">Nombre</th>
                            <th scope="col">Casa / Depto</th>
                            <th scope="col">Ubicación</th>
                            <th scope="col">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">1</th>
                            <td>Sala eventos A</td>
                            <td>19/01/2019 10:00</td>
                            <td>19/01/2019 19:00</td>
                            <td>5.555.555-5</td>
                            <td>Ernesto Alvarez Toledo</td>
                            <td>302</td>
                            <td>Torre Mahuida</td>
                            <td>
                                <select id="selection">
                                    <option value="volvo">accion 1</option>
                                    <option value="saab">accion 2</option>
                                    <option value="mercedes">accion 3</option>
                                    <option value="audi">accion 4</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">2</th>
                            <td>Sala eventos B</td>
                            <td>19/01/2019 10:00</td>
                            <td>19/01/2019 15:00</td>
                            <td>7.777.777-7</td>
                            <td>Miguel Toro Cares</td>
                            <td>35</td>
                            <td>Torre B</td>
                            <td></td>
                        </tr>
                        <tr>
                            <th scope="row">3</th>
                            <td>Sala eventos B</td>
                            <td>19/01/2019 16:00</td>
                            <td>19/01/2019 20:00</td>
                            <td>8.888.888-8</td>
                            <td>Jorge Mendez Fredes</td>
                            <td>Casa 01</td>
                            <td></td>
                            <td></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

    </div>

@*Modals*@
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" data-keyboard="false" data-backdrop="static">
    @*<partial name="Agregar" />
    @await Html.PartialAsync("Agregar")
    @await Component.InvokeAsync("RegistroSolicitudComponent", "Agregar")*@
</div>


@section scripts {

    <script src="~/js/registro-solicitud/index.js"></script>

}